Contact us inside user profile
ariannavalle/destination-finder pull request #42
Opened 2020-09-10 21:34 UTC by andreiAlvarez

2020-09-10 21:55 UTC, ariannavalle requested changes
Please remove "Contact us" from the user profile and instead create a brand new view that can be accessed from the "contact" link in the nav bar.

2020-09-11 18:53 UTC, kevin4052 approved these changes

2020-09-12 20:16 UTC, ariannavalle approved these changes

2020-09-12 20:16 UTC, merged

2020-09-12 20:34 UTC, andreiAlvarez reviewed
Changes reviewed!